export declare const env: {
    NODE_ENV: "development" | "test" | "production";
    PORT: number;
    HOST: string;
    API_PREFIX: string;
    DATABASE_URL: string;
    REDIS_HOST: string;
    REDIS_PORT: number;
    REDIS_DB: number;
    JWT_SECRET: string;
    JWT_EXPIRES_IN: string;
    JWT_REFRESH_SECRET: string;
    JWT_REFRESH_EXPIRES_IN: string;
    ENCRYPTION_KEY: string;
    META_API_VERSION: string;
    META_API_BASE_URL: string;
    META_APP_SECRET: string;
    META_REQUEST_TIMEOUT_MS: number;
    WEBHOOK_BASE_URL: string;
    WEBHOOK_PATH: string;
    QUEUE_MESSAGE_CONCURRENCY: number;
    QUEUE_CAMPAIGN_CONCURRENCY: number;
    QUEUE_WEBHOOK_CONCURRENCY: number;
    QUEUE_HEALTH_CONCURRENCY: number;
    QUEUE_GLOBAL_RATE_MAX: number;
    QUEUE_GLOBAL_RATE_DURATION_MS: number;
    HEALTH_CHECK_INTERVAL_MS: number;
    HEALTH_MAX_AUTH_ERRORS: number;
    HEALTH_MAX_RATE_ERRORS: number;
    HEALTH_MAX_TEMP_ERRORS: number;
    HEALTH_PAUSE_RATE_LIMIT_SECONDS: number;
    HEALTH_PAUSE_TEMP_ERROR_SECONDS: number;
    LOG_LEVEL: "trace" | "debug" | "info" | "warn" | "error" | "fatal";
    LOG_FORMAT: "pretty" | "json";
    CORS_ORIGINS: string;
    RATE_LIMIT_MAX: number;
    RATE_LIMIT_WINDOW_MS: number;
    BCRYPT_ROUNDS: number;
    DAILY_RESET_CRON: string;
    DAILY_RESET_TIMEZONE: string;
    REDIS_PASSWORD?: string | undefined;
    ANTHROPIC_API_KEY?: string | undefined;
};
export type Env = typeof env;
//# sourceMappingURL=env.d.ts.map