import { z } from 'zod';
export declare const createCampaignSchema: z.ZodEffects<z.ZodEffects<z.ZodObject<{
    name: z.ZodString;
    description: z.ZodOptional<z.ZodString>;
    templateId: z.ZodString;
    contactTags: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    allowedConnectionIds: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    contactFilter: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    scheduledAt: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    sendWindowStart: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    sendWindowEnd: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    timezone: z.ZodDefault<z.ZodString>;
    maxMessagesPerContact: z.ZodDefault<z.ZodNumber>;
    minIntervalSeconds: z.ZodDefault<z.ZodNumber>;
    maxIntervalSeconds: z.ZodDefault<z.ZodNumber>;
}, "strip", z.ZodTypeAny, {
    name: string;
    templateId: string;
    contactTags: string[];
    allowedConnectionIds: string[];
    timezone: string;
    maxMessagesPerContact: number;
    minIntervalSeconds: number;
    maxIntervalSeconds: number;
    description?: string | undefined;
    contactFilter?: Record<string, unknown> | undefined;
    scheduledAt?: string | null | undefined;
    sendWindowStart?: string | null | undefined;
    sendWindowEnd?: string | null | undefined;
}, {
    name: string;
    templateId: string;
    description?: string | undefined;
    contactTags?: string[] | undefined;
    allowedConnectionIds?: string[] | undefined;
    contactFilter?: Record<string, unknown> | undefined;
    scheduledAt?: string | null | undefined;
    sendWindowStart?: string | null | undefined;
    sendWindowEnd?: string | null | undefined;
    timezone?: string | undefined;
    maxMessagesPerContact?: number | undefined;
    minIntervalSeconds?: number | undefined;
    maxIntervalSeconds?: number | undefined;
}>, {
    name: string;
    templateId: string;
    contactTags: string[];
    allowedConnectionIds: string[];
    timezone: string;
    maxMessagesPerContact: number;
    minIntervalSeconds: number;
    maxIntervalSeconds: number;
    description?: string | undefined;
    contactFilter?: Record<string, unknown> | undefined;
    scheduledAt?: string | null | undefined;
    sendWindowStart?: string | null | undefined;
    sendWindowEnd?: string | null | undefined;
}, {
    name: string;
    templateId: string;
    description?: string | undefined;
    contactTags?: string[] | undefined;
    allowedConnectionIds?: string[] | undefined;
    contactFilter?: Record<string, unknown> | undefined;
    scheduledAt?: string | null | undefined;
    sendWindowStart?: string | null | undefined;
    sendWindowEnd?: string | null | undefined;
    timezone?: string | undefined;
    maxMessagesPerContact?: number | undefined;
    minIntervalSeconds?: number | undefined;
    maxIntervalSeconds?: number | undefined;
}>, {
    name: string;
    templateId: string;
    contactTags: string[];
    allowedConnectionIds: string[];
    timezone: string;
    maxMessagesPerContact: number;
    minIntervalSeconds: number;
    maxIntervalSeconds: number;
    description?: string | undefined;
    contactFilter?: Record<string, unknown> | undefined;
    scheduledAt?: string | null | undefined;
    sendWindowStart?: string | null | undefined;
    sendWindowEnd?: string | null | undefined;
}, {
    name: string;
    templateId: string;
    description?: string | undefined;
    contactTags?: string[] | undefined;
    allowedConnectionIds?: string[] | undefined;
    contactFilter?: Record<string, unknown> | undefined;
    scheduledAt?: string | null | undefined;
    sendWindowStart?: string | null | undefined;
    sendWindowEnd?: string | null | undefined;
    timezone?: string | undefined;
    maxMessagesPerContact?: number | undefined;
    minIntervalSeconds?: number | undefined;
    maxIntervalSeconds?: number | undefined;
}>;
export declare const updateCampaignSchema: z.ZodObject<{
    name: z.ZodOptional<z.ZodString>;
    description: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    templateId: z.ZodOptional<z.ZodString>;
    contactTags: z.ZodOptional<z.ZodDefault<z.ZodArray<z.ZodString, "many">>>;
    allowedConnectionIds: z.ZodOptional<z.ZodDefault<z.ZodArray<z.ZodString, "many">>>;
    contactFilter: z.ZodOptional<z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>>;
    scheduledAt: z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>;
    sendWindowStart: z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>;
    sendWindowEnd: z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>;
    timezone: z.ZodOptional<z.ZodDefault<z.ZodString>>;
    maxMessagesPerContact: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
    minIntervalSeconds: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
    maxIntervalSeconds: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
}, "strip", z.ZodTypeAny, {
    name?: string | undefined;
    templateId?: string | undefined;
    description?: string | undefined;
    contactTags?: string[] | undefined;
    allowedConnectionIds?: string[] | undefined;
    contactFilter?: Record<string, unknown> | undefined;
    scheduledAt?: string | null | undefined;
    sendWindowStart?: string | null | undefined;
    sendWindowEnd?: string | null | undefined;
    timezone?: string | undefined;
    maxMessagesPerContact?: number | undefined;
    minIntervalSeconds?: number | undefined;
    maxIntervalSeconds?: number | undefined;
}, {
    name?: string | undefined;
    templateId?: string | undefined;
    description?: string | undefined;
    contactTags?: string[] | undefined;
    allowedConnectionIds?: string[] | undefined;
    contactFilter?: Record<string, unknown> | undefined;
    scheduledAt?: string | null | undefined;
    sendWindowStart?: string | null | undefined;
    sendWindowEnd?: string | null | undefined;
    timezone?: string | undefined;
    maxMessagesPerContact?: number | undefined;
    minIntervalSeconds?: number | undefined;
    maxIntervalSeconds?: number | undefined;
}>;
export declare const listCampaignsSchema: z.ZodObject<{
    page: z.ZodDefault<z.ZodNumber>;
    limit: z.ZodDefault<z.ZodNumber>;
    status: z.ZodOptional<z.ZodNativeEnum<{
        DRAFT: "DRAFT";
        SCHEDULED: "SCHEDULED";
        RUNNING: "RUNNING";
        PAUSED: "PAUSED";
        FINISHED: "FINISHED";
        ERROR: "ERROR";
    }>>;
    search: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    page: number;
    limit: number;
    status?: "PAUSED" | "ERROR" | "DRAFT" | "SCHEDULED" | "RUNNING" | "FINISHED" | undefined;
    search?: string | undefined;
}, {
    status?: "PAUSED" | "ERROR" | "DRAFT" | "SCHEDULED" | "RUNNING" | "FINISHED" | undefined;
    search?: string | undefined;
    page?: number | undefined;
    limit?: number | undefined;
}>;
export type CreateCampaignInput = z.infer<typeof createCampaignSchema>;
export type UpdateCampaignInput = z.infer<typeof updateCampaignSchema>;
export type ListCampaignsInput = z.infer<typeof listCampaignsSchema>;
//# sourceMappingURL=campaigns.schema.d.ts.map